v = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(v))
print('Tem espaços?: ',v.isspace())
print('É um numero?: ',v.isnumeric())
print('É alfabético?: ',v.isalpha())
print('É alfanumerico?: ',v.isalnum())
print('Está em maiúsculas?: ',v.isupper())
print('Está em minúsculas?: ',v.islower())
print('Está capitalizada?: ',v.istitle())